AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template to create an S3-triggered Lambda that stores image metadata in DynamoDB.

Parameters:
  EnvName:
    Type: String
    Default: "dev"
    Description: Environnement name
  VPcId:
    Type: String
    Default: "vpc-0b5f3f9b482b7b7a4"
    Description: VPC ID for the EC2 instance

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: S3LambdaPermission  # important!
    Properties:
      BucketName: !Sub "${EnvName}-file-metadata-bucket"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt LambdaFunction.Arn

  S3LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::${EnvName}-file-metadata-bucket"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "FileMetadata-${EnvName}"
      AttributeDefinitions:
        - AttributeName: "FileName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "FileName"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  MysecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${EnvName}-security-group"
      GroupDescription: "Security group for MessanADABRA-instance"
      VpcId: !Ref VPcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 196.171.37.12/24

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "learn-function-${EnvName}"
      Role: "arn:aws:iam::629193321657:role/lambda-s3-trigger-role"
      Runtime: python3.9
      Handler: index.lambda_handler
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          DDB_TABLE_NAME: !Sub "FileMetadata-${EnvName}"
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          def lambda_handler(event, context):
              s3 = boto3.client('s3')
              dynamodb = boto3.resource('dynamodb')
              table_name = os.environ['DDB_TABLE_NAME']
              table = dynamodb.Table(table_name)

              for record in event['Records']:
                  bucket = record['s3']['bucket']['name']
                  key = record['s3']['object']['key']
                  response = table.put_item(
                      Item={
                          'FileName': key,
                          'BucketName': bucket
                      }
                  )
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!')
              }
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0160e8d70ebc43ee1"
      InstanceType: t2.micro
      KeyName: "iabdkey"
      SubnetId: subnet-0a230d78bf307974b
      SecurityGroupIds:
        - sg-05aa54c7bba3d1658
      BlockDeviceMappings: 
        - DeviceName: "/dev/sdm"
          Ebs: 
            VolumeType: "io1"
            Iops: "200"
            DeleteOnTermination: "true"
            VolumeSize: "20"
        - DeviceName: "/dev/sdk"
          NoDevice: {}
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y

          # Install unzip and curl
          yum install -y unzip curl

          # Download and install AWS CLI v2
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install

          # Add AWS CLI to PATH for all users
          echo 'export PATH=/usr/local/bin:$PATH' >> /etc/profile.d/awscli.sh
          source /etc/profile

          # Verify installation
          aws --version
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-EC2-instance"
        - Key: Class
          Value: iabd
